## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head(2)

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(['EIN'], axis=1, inplace= True)
application_df.head(2)

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1

In [ ]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [ ]:
name_count = application_df.NAME.value_counts()
name_count

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [ ]:
for name in name_count[name_count<6].index:
  application_df.NAME = application_df.NAME.replace(name,'Other')
application_df.NAME.value_counts()

Other                                           20043
PARENT BOOSTER USA INC                           1260
TOPS CLUB INC                                     765
UNITED STATES BOWLING CONGRESS INC                700
WASHINGTON STATE UNIVERSITY                       492
                                                ...
HABITAT FOR HUMANITY INTERNATIONAL                  6
DAMAGE PREVENTION COUNCIL OF TEXAS                  6
FLEET RESERVE ASSOCIATION                           6
HUGH OBRIAN YOUTH LEADERSHIP                        6
INTERNATIONAL CONGRESS OF CHURCHES MINISTERS        6
Name: NAME, Length: 355, dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
app_count = application_df['APPLICATION_TYPE'].value_counts()
app_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
app_count[app_count < 500].index

Index(['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17'], dtype='object')

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = app_count[app_count < 500].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
count = application_df['CLASSIFICATION'].value_counts()
count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
filter = count[count>1]
filter

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = [count[count<550].keys()]

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [ ]:
application_df.nunique()

NAME                       355
APPLICATION_TYPE             9
AFFILIATION                  6
CLASSIFICATION               7
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`

application_df= pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [ ]:
#ensure that all catagorical are now numerical
application_df.dtypes

STATUS                                    int64
ASK_AMT                                   int64
IS_SUCCESSFUL                             int64
NAME_AACE INTERNATIONAL                   uint8
NAME_ACE MENTOR PROGRAM OF AMERICA INC    uint8
                                          ...
INCOME_AMT_25000-99999                    uint8
INCOME_AMT_50M+                           uint8
INCOME_AMT_5M-10M                         uint8
SPECIAL_CONSIDERATIONS_N                  uint8
SPECIAL_CONSIDERATIONS_Y                  uint8
Length: 400, dtype: object

In [ ]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL']
#drop the target
application_df.drop('IS_SUCCESSFUL', axis=1, inplace=True)
X= application_df
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 85)

# Split the preprocessed data into a training and testing dataset

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
len(X_train_scaled[0])

399

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
features = len(X_train_scaled[0])
model = tf.keras.models.Sequential()
# First hidden layer
model.add(tf.keras.layers.Dense(units=80, activation="relu", input_dim=features))

# Second hidden layer
model.add(tf.keras.layers.Dense(units=30, activation="sigmoid"))

# Output layer
model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 80)                32000

 dense_10 (Dense)            (None, 30)                2430

 dense_11 (Dense)            (None, 1)                 31

=================================================================
Total params: 34461 (134.61 KB)
Trainable params: 34461 (134.61 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
print(f"X_train_scaled shape: {X_train_scaled.shape}")
print(f"y_train shape: {y_train.shape}")

X_train_scaled shape: (25724, 399)
y_train shape: (25724,)

In [ ]:
# Train the model
fit_model = model.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4728 - accuracy: 0.7760
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4345 - accuracy: 0.7927
Epoch 3/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4298 - accuracy: 0.7936
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4275 - accuracy: 0.7959
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4260 - accuracy: 0.7968
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4240 - accuracy: 0.7972
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4235 - accuracy: 0.7968
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4214 - accuracy: 0.7991
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4212 - accuracy: 0.7980
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4200 - accuracy: 0.7991
Epoch 11/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4196 - accuracy: 0.7995
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4189 - accuracy: 0.7998
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4176 - accuracy: 0.8007
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4178 - accuracy: 0.7989
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4167 - accuracy: 0.8000
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4159 - accuracy: 0.7997
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4161 - accuracy: 0.7990
Epoch 18/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4152 - accuracy: 0.8014
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4147 - accuracy: 0.8000
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4145 - accuracy: 0.8028
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4140 - accuracy: 0.8005
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4133 - accuracy: 0.8019
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4133 - accuracy: 0.8019
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4122 - accuracy: 0.8029
Epoch 25/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4122 - accuracy: 0.8026
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4115 - accuracy: 0.8028
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4116 - accuracy: 0.8032
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4110 - accuracy: 0.8045
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4108 - accuracy: 0.8029
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4103 - accuracy: 0.8029
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4100 - accuracy: 0.8046
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4096 - accuracy: 0.8043
Epoch 33/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4093 - accuracy: 0.8036
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4089 - accuracy: 0.8029
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4087 - accuracy: 0.8043
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4084 - accuracy: 0.8046
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4080 - accuracy: 0.8051
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4078 - accuracy: 0.8050
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4080 - accuracy: 0.8031
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4074 - accuracy: 0.8046
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4071 - accuracy: 0.8050
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4071 - accuracy: 0.8053
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4070 - accuracy: 0.8051
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4062 - accuracy: 0.8048
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4060 - accuracy: 0.8052
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4063 - accuracy: 0.8056
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4059 - accuracy: 0.8057
Epoch 48/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4055 - accuracy: 0.8043
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4059 - accuracy: 0.8057
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4055 - accuracy: 0.8060

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.4421 - accuracy: 0.7934 - 481ms/epoch - 2ms/step
Loss: 0.44209614396095276, Accuracy: 0.7933527827262878

In [ ]:
model.save('CharityOptimazation2.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(